// Pre-defined crafting recipes for offline play
// Format: "element1+element2" -> { name, emoji }

export interface Recipe {
  name: string;
  emoji: string;
}

const recipes: Record<string, Recipe> = {
  // Basic combinations with Water
  "water+fire": { name: "Steam", emoji: "💨" },
  "fire+water": { name: "Steam", emoji: "💨" },
  "water+earth": { name: "Mud", emoji: "🟤" },
  "earth+water": { name: "Mud", emoji: "🟤" },
  "water+wind": { name: "Wave", emoji: "🌊" },
  "wind+water": { name: "Wave", emoji: "🌊" },
  "water+water": { name: "Lake", emoji: "🏞️" },

  // Basic combinations with Fire
  "fire+earth": { name: "Lava", emoji: "🌋" },
  "earth+fire": { name: "Lava", emoji: "🌋" },
  "fire+wind": { name: "Smoke", emoji: "💨" },
  "wind+fire": { name: "Smoke", emoji: "💨" },
  "fire+fire": { name: "Energy", emoji: "⚡" },

  // Basic combinations with Earth
  "earth+wind": { name: "Dust", emoji: "🌫️" },
  "wind+earth": { name: "Dust", emoji: "🌫️" },
  "earth+earth": { name: "Mountain", emoji: "⛰️" },

  // Basic combinations with Wind
  "wind+wind": { name: "Tornado", emoji: "🌪️" },

  // Second tier combinations
  "steam+fire": { name: "Engine", emoji: "🚂" },
  "fire+steam": { name: "Engine", emoji: "🚂" },
  "steam+water": { name: "Cloud", emoji: "☁️" },
  "water+steam": { name: "Cloud", emoji: "☁️" },
  "steam+earth": { name: "Geyser", emoji: "♨️" },
  "earth+steam": { name: "Geyser", emoji: "♨️" },
  "steam+wind": { name: "Cloud", emoji: "☁️" },
  "wind+steam": { name: "Cloud", emoji: "☁️" },

  "mud+fire": { name: "Brick", emoji: "🧱" },
  "fire+mud": { name: "Brick", emoji: "🧱" },
  "mud+water": { name: "Swamp", emoji: "🐊" },
  "water+mud": { name: "Swamp", emoji: "🐊" },
  "mud+wind": { name: "Clay", emoji: "🏺" },
  "wind+mud": { name: "Clay", emoji: "🏺" },
  "mud+earth": { name: "Clay", emoji: "🏺" },
  "earth+mud": { name: "Clay", emoji: "🏺" },

  "wave+fire": { name: "Steam", emoji: "💨" },
  "fire+wave": { name: "Steam", emoji: "💨" },
  "wave+earth": { name: "Beach", emoji: "🏖️" },
  "earth+wave": { name: "Beach", emoji: "🏖️" },
  "wave+wind": { name: "Tsunami", emoji: "🌊" },
  "wind+wave": { name: "Tsunami", emoji: "🌊" },
  "wave+wave": { name: "Tsumani", emoji: "🌊" },

  "lake+fire": { name: "Steam", emoji: "💨" },
  "fire+lake": { name: "Steam", emoji: "💨" },
  "lake+earth": { name: "Island", emoji: "🏝️" },
  "earth+lake": { name: "Island", emoji: "🏝️" },
  "lake+wind": { name: "Wave", emoji: "🌊" },
  "wind+lake": { name: "Wave", emoji: "🌊" },
  "lake+lake": { name: "Ocean", emoji: "🌊" },

  "lava+water": { name: "Stone", emoji: "🪨" },
  "water+lava": { name: "Stone", emoji: "🪨" },
  "lava+wind": { name: "Rock", emoji: "🪨" },
  "wind+lava": { name: "Rock", emoji: "🪨" },
  "lava+earth": { name: "Volcano", emoji: "🌋" },
  "earth+lava": { name: "Volcano", emoji: "🌋" },
  "lava+fire": { name: "Volcano", emoji: "🌋" },
  "fire+lava": { name: "Volcano", emoji: "🌋" },

  "smoke+water": { name: "Fog", emoji: "🌫️" },
  "water+smoke": { name: "Fog", emoji: "🌫️" },
  "smoke+earth": { name: "Ash", emoji: "🌑" },
  "earth+smoke": { name: "Ash", emoji: "🌑" },
  "smoke+wind": { name: "Smog", emoji: "🌫️" },
  "wind+smoke": { name: "Smog", emoji: "🌫️" },
  "smoke+fire": { name: "Ash", emoji: "🌑" },
  "fire+smoke": { name: "Ash", emoji: "🌑" },

  "dust+water": { name: "Mud", emoji: "🟤" },
  "water+dust": { name: "Mud", emoji: "🟤" },
  "dust+fire": { name: "Ash", emoji: "🌑" },
  "fire+dust": { name: "Ash", emoji: "🌑" },
  "dust+wind": { name: "Sandstorm", emoji: "🏜️" },
  "wind+dust": { name: "Sandstorm", emoji: "🏜️" },

  "mountain+water": { name: "River", emoji: "🏞️" },
  "water+mountain": { name: "River", emoji: "🏞️" },
  "mountain+fire": { name: "Volcano", emoji: "🌋" },
  "fire+mountain": { name: "Volcano", emoji: "🌋" },
  "mountain+wind": { name: "Avalanche", emoji: "❄️" },
  "wind+mountain": { name: "Avalanche", emoji: "❄️" },
  "mountain+earth": { name: "Mountain Range", emoji: "🏔️" },
  "earth+mountain": { name: "Mountain Range", emoji: "🏔️" },
  "mountain+mountain": { name: "Mountain Range", emoji: "🏔️" },

  "tornado+fire": { name: "Fire Tornado", emoji: "🔥" },
  "fire+tornado": { name: "Fire Tornado", emoji: "🔥" },
  "tornado+water": { name: "Hurricane", emoji: "🌀" },
  "water+tornado": { name: "Hurricane", emoji: "🌀" },
  "tornado+earth": { name: "Sandstorm", emoji: "🏜️" },
  "earth+tornado": { name: "Sandstorm", emoji: "🏜️" },

  "energy+water": { name: "Life", emoji: "🧬" },
  "water+energy": { name: "Life", emoji: "🧬" },
  "energy+earth": { name: "Earthquake", emoji: "💥" },
  "earth+energy": { name: "Earthquake", emoji: "💥" },
  "energy+wind": { name: "Storm", emoji: "⛈️" },
  "wind+energy": { name: "Storm", emoji: "⛈️" },
  "energy+fire": { name: "Plasma", emoji: "✨" },
  "fire+energy": { name: "Plasma", emoji: "✨" },

  // Third tier combinations
  "cloud+water": { name: "Rain", emoji: "🌧️" },
  "water+cloud": { name: "Rain", emoji: "🌧️" },
  "cloud+fire": { name: "Lightning", emoji: "⚡" },
  "fire+cloud": { name: "Lightning", emoji: "⚡" },
  "cloud+earth": { name: "Fog", emoji: "🌫️" },
  "earth+cloud": { name: "Fog", emoji: "🌫️" },
  "cloud+wind": { name: "Storm", emoji: "⛈️" },
  "wind+cloud": { name: "Storm", emoji: "⛈️" },
  "cloud+cloud": { name: "Rain", emoji: "🌧️" },

  "rain+fire": { name: "Rainbow", emoji: "🌈" },
  "fire+rain": { name: "Rainbow", emoji: "🌈" },
  "rain+earth": { name: "Plant", emoji: "🌱" },
  "earth+rain": { name: "Plant", emoji: "🌱" },
  "rain+wind": { name: "Storm", emoji: "⛈️" },
  "wind+rain": { name: "Storm", emoji: "⛈️" },
  "rain+water": { name: "Flood", emoji: "🌊" },
  "water+rain": { name: "Flood", emoji: "🌊" },

  "stone+fire": { name: "Metal", emoji: "🔩" },
  "fire+stone": { name: "Metal", emoji: "🔩" },
  "stone+water": { name: "Sand", emoji: "🏖️" },
  "water+stone": { name: "Sand", emoji: "🏖️" },
  "stone+wind": { name: "Sand", emoji: "🏖️" },
  "wind+stone": { name: "Sand", emoji: "🏖️" },
  "stone+stone": { name: "Boulder", emoji: "🪨" },

  "rock+fire": { name: "Metal", emoji: "🔩" },
  "fire+rock": { name: "Metal", emoji: "🔩" },
  "rock+water": { name: "Sand", emoji: "🏖️" },
  "water+rock": { name: "Sand", emoji: "🏖️" },
  "rock+wind": { name: "Sand", emoji: "🏖️" },
  "wind+rock": { name: "Sand", emoji: "🏖️" },

  "brick+brick": { name: "Wall", emoji: "🧱" },
  "brick+fire": { name: "Furnace", emoji: "🔥" },
  "fire+brick": { name: "Furnace", emoji: "🔥" },
  "brick+water": { name: "House", emoji: "🏠" },
  "water+brick": { name: "House", emoji: "🏠" },

  "clay+fire": { name: "Pottery", emoji: "🏺" },
  "fire+clay": { name: "Pottery", emoji: "🏺" },
  "clay+water": { name: "Mud", emoji: "🟤" },
  "water+clay": { name: "Mud", emoji: "🟤" },

  "swamp+fire": { name: "Peat", emoji: "🟤" },
  "fire+swamp": { name: "Peat", emoji: "🟤" },
  "swamp+earth": { name: "Fossil", emoji: "🦴" },
  "earth+swamp": { name: "Fossil", emoji: "🦴" },
  "swamp+life": { name: "Frog", emoji: "🐸" },
  "life+swamp": { name: "Frog", emoji: "🐸" },

  "beach+fire": { name: "Glass", emoji: "🔮" },
  "fire+beach": { name: "Glass", emoji: "🔮" },
  "beach+water": { name: "Ocean", emoji: "🌊" },
  "water+beach": { name: "Ocean", emoji: "🌊" },
  "beach+wind": { name: "Sandcastle", emoji: "🏰" },
  "wind+beach": { name: "Sandcastle", emoji: "🏰" },

  "ocean+fire": { name: "Steam", emoji: "💨" },
  "fire+ocean": { name: "Steam", emoji: "💨" },
  "ocean+earth": { name: "Island", emoji: "🏝️" },
  "earth+ocean": { name: "Island", emoji: "🏝️" },
  "ocean+wind": { name: "Wave", emoji: "🌊" },
  "wind+ocean": { name: "Wave", emoji: "🌊" },
  "ocean+life": { name: "Fish", emoji: "🐟" },
  "life+ocean": { name: "Fish", emoji: "🐟" },
  "ocean+ocean": { name: "Sea", emoji: "🌊" },
  "sea+sea": { name: "Ocean", emoji: "🌊" },

  "island+fire": { name: "Volcano", emoji: "🌋" },
  "fire+island": { name: "Volcano", emoji: "🌋" },
  "island+life": { name: "Animal", emoji: "🐒" },
  "life+island": { name: "Animal", emoji: "🐒" },

  "volcano+water": { name: "Stone", emoji: "🪨" },
  "water+volcano": { name: "Stone", emoji: "🪨" },
  "volcano+wind": { name: "Ash", emoji: "🌑" },
  "wind+volcano": { name: "Ash", emoji: "🌑" },

  "river+fire": { name: "Steam", emoji: "💨" },
  "fire+river": { name: "Steam", emoji: "💨" },
  "river+earth": { name: "Delta", emoji: "🏝️" },
  "earth+river": { name: "Delta", emoji: "🏝️" },
  "river+life": { name: "Fish", emoji: "🐟" },
  "life+river": { name: "Fish", emoji: "🐟" },

  "life+earth": { name: "Human", emoji: "👤" },
  "earth+life": { name: "Human", emoji: "👤" },
  "life+fire": { name: "Phoenix", emoji: "🦅" },
  "fire+life": { name: "Phoenix", emoji: "🦅" },
  "life+wind": { name: "Bird", emoji: "🐦" },
  "wind+life": { name: "Bird", emoji: "🐦" },
  "life+water": { name: "Fish", emoji: "🐟" },
  "water+life": { name: "Fish", emoji: "🐟" },
  "life+life": { name: "Love", emoji: "❤️" },

  "plant+fire": { name: "Smoke", emoji: "💨" },
  "fire+plant": { name: "Smoke", emoji: "💨" },
  "plant+water": { name: "Tree", emoji: "🌳" },
  "water+plant": { name: "Tree", emoji: "🌳" },
  "plant+earth": { name: "Tree", emoji: "🌳" },
  "earth+plant": { name: "Tree", emoji: "🌳" },
  "plant+wind": { name: "Flower", emoji: "🌸" },
  "wind+plant": { name: "Flower", emoji: "🌸" },
  "plant+plant": { name: "Garden", emoji: "🌻" },

  "tree+fire": { name: "Coal", emoji: "⬛" },
  "fire+tree": { name: "Coal", emoji: "⬛" },
  "tree+wind": { name: "Leaf", emoji: "🍃" },
  "wind+tree": { name: "Leaf", emoji: "🍃" },
  "tree+tree": { name: "Forest", emoji: "🌲" },
  "tree+water": { name: "Fruit", emoji: "🍎" },
  "water+tree": { name: "Fruit", emoji: "🍎" },

  "forest+fire": { name: "Coal", emoji: "⬛" },
  "fire+forest": { name: "Coal", emoji: "⬛" },
  "forest+wind": { name: "Leaf", emoji: "🍃" },
  "wind+forest": { name: "Leaf", emoji: "🍃" },
  "forest+animal": { name: "Wild Animal", emoji: "🦌" },
  "animal+forest": { name: "Wild Animal", emoji: "🦌" },
  "forest+human": { name: "Wood", emoji: "🪵" },
  "human+forest": { name: "Wood", emoji: "🪵" },

  "human+fire": { name: "Cook", emoji: "👨‍🍳" },
  "fire+human": { name: "Cook", emoji: "👨‍🍳" },
  "human+water": { name: "Swimmer", emoji: "🏊" },
  "water+human": { name: "Swimmer", emoji: "🏊" },
  "human+wind": { name: "Pilot", emoji: "✈️" },
  "wind+human": { name: "Pilot", emoji: "✈️" },
  "human+earth": { name: "Farmer", emoji: "👨‍🌾" },
  "earth+human": { name: "Farmer", emoji: "👨‍🌾" },
  "human+human": { name: "Family", emoji: "👨‍👩‍👧" },
  "human+metal": { name: "Tool", emoji: "🔧" },
  "metal+human": { name: "Tool", emoji: "🔧" },

  "metal+fire": { name: "Sword", emoji: "⚔️" },
  "fire+metal": { name: "Sword", emoji: "⚔️" },
  "metal+water": { name: "Rust", emoji: "🟤" },
  "water+metal": { name: "Rust", emoji: "🟤" },
  "metal+wind": { name: "Bell", emoji: "🔔" },
  "wind+metal": { name: "Bell", emoji: "🔔" },
  "metal+earth": { name: "Ore", emoji: "⛏️" },
  "earth+metal": { name: "Ore", emoji: "⛏️" },
  "metal+metal": { name: "Alloy", emoji: "🔩" },

  "sand+fire": { name: "Glass", emoji: "🔮" },
  "fire+sand": { name: "Glass", emoji: "🔮" },
  "sand+water": { name: "Quicksand", emoji: "🏖️" },
  "water+sand": { name: "Quicksand", emoji: "🏖️" },
  "sand+wind": { name: "Dune", emoji: "🏜️" },
  "wind+sand": { name: "Dune", emoji: "🏜️" },
  "sand+sand": { name: "Desert", emoji: "🏜️" },

  "glass+fire": { name: "Lens", emoji: "🔍" },
  "fire+glass": { name: "Lens", emoji: "🔍" },
  "glass+water": { name: "Aquarium", emoji: "🐠" },
  "water+glass": { name: "Aquarium", emoji: "🐠" },
  "glass+wind": { name: "Chime", emoji: "🎐" },
  "wind+glass": { name: "Chime", emoji: "🎐" },

  "lightning+water": { name: "Life", emoji: "🧬" },
  "water+lightning": { name: "Life", emoji: "🧬" },
  "lightning+earth": { name: "Fulgurite", emoji: "⚡" },
  "earth+lightning": { name: "Fulgurite", emoji: "⚡" },
  "lightning+wind": { name: "Thunder", emoji: "🌩️" },
  "wind+lightning": { name: "Thunder", emoji: "🌩️" },
  "lightning+fire": { name: "Plasma", emoji: "✨" },
  "fire+lightning": { name: "Plasma", emoji: "✨" },
  "lightning+metal": { name: "Electricity", emoji: "⚡" },
  "metal+lightning": { name: "Electricity", emoji: "⚡" },

  "storm+fire": { name: "Lightning", emoji: "⚡" },
  "fire+storm": { name: "Lightning", emoji: "⚡" },
  "storm+earth": { name: "Flood", emoji: "🌊" },
  "earth+storm": { name: "Flood", emoji: "🌊" },
  "storm+water": { name: "Flood", emoji: "🌊" },
  "water+storm": { name: "Flood", emoji: "🌊" },
  "storm+ocean": { name: "Hurricane", emoji: "🌀" },
  "ocean+storm": { name: "Hurricane", emoji: "🌀" },

  "hurricane+earth": { name: "Destruction", emoji: "💥" },
  "earth+hurricane": { name: "Destruction", emoji: "💥" },
  "hurricane+fire": { name: "Chaos", emoji: "🔥" },
  "fire+hurricane": { name: "Chaos", emoji: "🔥" },

  "rainbow+water": { name: "Color", emoji: "🎨" },
  "water+rainbow": { name: "Color", emoji: "🎨" },
  "rainbow+fire": { name: "Color", emoji: "🎨" },
  "fire+rainbow": { name: "Color", emoji: "🎨" },
  "rainbow+earth": { name: "Pot of Gold", emoji: "💰" },
  "earth+rainbow": { name: "Pot of Gold", emoji: "💰" },

  "fog+fire": { name: "Clear", emoji: "☀️" },
  "fire+fog": { name: "Clear", emoji: "☀️" },
  "fog+wind": { name: "Clear", emoji: "☀️" },
  "wind+fog": { name: "Clear", emoji: "☀️" },

  "ash+water": { name: "Mud", emoji: "🟤" },
  "water+ash": { name: "Mud", emoji: "🟤" },
  "ash+wind": { name: "Dust", emoji: "🌫️" },
  "wind+ash": { name: "Dust", emoji: "🌫️" },

  "coal+fire": { name: "Diamond", emoji: "💎" },
  "fire+coal": { name: "Diamond", emoji: "💎" },
  "coal+wind": { name: "Smoke", emoji: "💨" },
  "wind+coal": { name: "Smoke", emoji: "💨" },

  "diamond+fire": { name: "Jewelry", emoji: "💍" },
  "fire+diamond": { name: "Jewelry", emoji: "💍" },
  "diamond+human": { name: "Ring", emoji: "💍" },
  "human+diamond": { name: "Ring", emoji: "💍" },

  "bird+fire": { name: "Phoenix", emoji: "🦅" },
  "fire+bird": { name: "Phoenix", emoji: "🦅" },
  "bird+water": { name: "Duck", emoji: "🦆" },
  "water+bird": { name: "Duck", emoji: "🦆" },
  "bird+bird": { name: "Flock", emoji: "🐦" },
  "bird+tree": { name: "Nest", emoji: "🪺" },
  "tree+bird": { name: "Nest", emoji: "🪺" },

  "fish+fire": { name: "Sushi", emoji: "🍣" },
  "fire+fish": { name: "Sushi", emoji: "🍣" },
  "fish+earth": { name: "Fossil", emoji: "🦴" },
  "earth+fish": { name: "Fossil", emoji: "🦴" },
  "fish+fish": { name: "School", emoji: "🐟" },
  "fish+human": { name: "Fishing", emoji: "🎣" },
  "human+fish": { name: "Fishing", emoji: "🎣" },

  "animal+fire": { name: "Barbecue", emoji: "🍖" },
  "fire+animal": { name: "Barbecue", emoji: "🍖" },
  "animal+water": { name: "Hippo", emoji: "🦛" },
  "water+animal": { name: "Hippo", emoji: "🦛" },
  "animal+wind": { name: "Eagle", emoji: "🦅" },
  "wind+animal": { name: "Eagle", emoji: "🦅" },
  "animal+earth": { name: "Worm", emoji: "🪱" },
  "earth+animal": { name: "Worm", emoji: "🪱" },
  "animal+human": { name: "Pet", emoji: "🐕" },
  "human+animal": { name: "Pet", emoji: "🐕" },

  "frog+fire": { name: "Prince", emoji: "🤴" },
  "fire+frog": { name: "Prince", emoji: "🤴" },
  "frog+human": { name: "Prince", emoji: "🤴" },
  "human+frog": { name: "Prince", emoji: "🤴" },

  "love+human": { name: "Baby", emoji: "👶" },
  "human+love": { name: "Baby", emoji: "👶" },
  "love+fire": { name: "Passion", emoji: "💕" },
  "fire+love": { name: "Passion", emoji: "💕" },
  "love+water": { name: "Tears", emoji: "😢" },
  "water+love": { name: "Tears", emoji: "😢" },

  "family+house": { name: "Home", emoji: "🏡" },
  "house+family": { name: "Home", emoji: "🏡" },
  "family+fire": { name: "Warmth", emoji: "🔥" },
  "fire+family": { name: "Warmth", emoji: "🔥" },

  "house+fire": { name: "Ruins", emoji: "🏚️" },
  "fire+house": { name: "Ruins", emoji: "🏚️" },
  "house+wind": { name: "Windmill", emoji: "🌀" },
  "wind+house": { name: "Windmill", emoji: "🌀" },
  "house+house": { name: "Village", emoji: "🏘️" },
  "house+human": { name: "Home", emoji: "🏡" },
  "human+house": { name: "Home", emoji: "🏡" },

  "village+village": { name: "City", emoji: "🌆" },
  "village+house": { name: "Town", emoji: "🏘️" },
  "house+village": { name: "Town", emoji: "🏘️" },

  "city+fire": { name: "Disaster", emoji: "💥" },
  "fire+city": { name: "Disaster", emoji: "💥" },
  "city+water": { name: "Flood", emoji: "🌊" },
  "water+city": { name: "Flood", emoji: "🌊" },
  "city+human": { name: "Population", emoji: "👥" },
  "human+city": { name: "Population", emoji: "👥" },

  "wall+wall": { name: "Room", emoji: "🚪" },
  "wall+house": { name: "Castle", emoji: "🏰" },
  "house+wall": { name: "Castle", emoji: "🏰" },

  "castle+human": { name: "King", emoji: "👑" },
  "human+castle": { name: "King", emoji: "👑" },
  "castle+fire": { name: "Dragon", emoji: "🐉" },
  "fire+castle": { name: "Dragon", emoji: "🐉" },

  "king+human": { name: "Queen", emoji: "👸" },
  "human+king": { name: "Queen", emoji: "👸" },
  "king+castle": { name: "Kingdom", emoji: "🏰" },
  "castle+king": { name: "Kingdom", emoji: "🏰" },

  "dragon+fire": { name: "Fire Dragon", emoji: "🐲" },
  "fire+dragon": { name: "Fire Dragon", emoji: "🐲" },
  "dragon+water": { name: "Sea Dragon", emoji: "🐉" },
  "water+dragon": { name: "Sea Dragon", emoji: "🐉" },
  "dragon+human": { name: "Hero", emoji: "🦸" },
  "human+dragon": { name: "Hero", emoji: "🦸" },

  "sword+human": { name: "Warrior", emoji: "⚔️" },
  "human+sword": { name: "Warrior", emoji: "⚔️" },
  "sword+dragon": { name: "Legend", emoji: "📜" },
  "dragon+sword": { name: "Legend", emoji: "📜" },

  "tool+tree": { name: "Wood", emoji: "🪵" },
  "tree+tool": { name: "Wood", emoji: "🪵" },
  "tool+stone": { name: "Carving", emoji: "🗿" },
  "stone+tool": { name: "Carving", emoji: "🗿" },
  "tool+metal": { name: "Machine", emoji: "⚙️" },
  "metal+tool": { name: "Machine", emoji: "⚙️" },

  "wood+fire": { name: "Coal", emoji: "⬛" },
  "fire+wood": { name: "Coal", emoji: "⬛" },
  "wood+water": { name: "Boat", emoji: "⛵" },
  "water+wood": { name: "Boat", emoji: "⛵" },
  "wood+human": { name: "House", emoji: "🏠" },
  "human+wood": { name: "House", emoji: "🏠" },
  "wood+tool": { name: "Furniture", emoji: "🪑" },
  "tool+wood": { name: "Furniture", emoji: "🪑" },

  "boat+wind": { name: "Sailboat", emoji: "⛵" },
  "wind+boat": { name: "Sailboat", emoji: "⛵" },
  "boat+human": { name: "Sailor", emoji: "⚓" },
  "human+boat": { name: "Sailor", emoji: "⚓" },
  "boat+ocean": { name: "Ship", emoji: "🚢" },
  "ocean+boat": { name: "Ship", emoji: "🚢" },

  "ship+wind": { name: "Voyage", emoji: "🧭" },
  "wind+ship": { name: "Voyage", emoji: "🧭" },
  "ship+island": { name: "Discovery", emoji: "🗺️" },
  "island+ship": { name: "Discovery", emoji: "🗺️" },

  "machine+human": { name: "Robot", emoji: "🤖" },
  "human+machine": { name: "Robot", emoji: "🤖" },
  "machine+fire": { name: "Engine", emoji: "🚂" },
  "fire+machine": { name: "Engine", emoji: "🚂" },
  "machine+water": { name: "Pump", emoji: "⛽" },
  "water+machine": { name: "Pump", emoji: "⛽" },
  "machine+wind": { name: "Fan", emoji: "🌀" },
  "wind+machine": { name: "Fan", emoji: "🌀" },

  "robot+human": { name: "Cyborg", emoji: "🦾" },
  "human+robot": { name: "Cyborg", emoji: "🦾" },
  "robot+fire": { name: "Terminator", emoji: "🤖" },
  "fire+robot": { name: "Terminator", emoji: "🤖" },

  "engine+water": { name: "Steamship", emoji: "🚢" },
  "water+engine": { name: "Steamship", emoji: "🚢" },
  "engine+wind": { name: "Plane", emoji: "✈️" },
  "wind+engine": { name: "Plane", emoji: "✈️" },
  "engine+earth": { name: "Train", emoji: "🚂" },
  "earth+engine": { name: "Train", emoji: "🚂" },
  "engine+sea": { name: "Submarine", emoji: "🛳️" },
  "sea+engine": { name: "Submarine", emoji: "🛳️" },
  "engine+ocean": { name: "Submarine", emoji: "🛳️" },
  "ocean+engine": { name: "Submarine", emoji: "🛳️" },
  "boat+engine": { name: "Submarine", emoji: "🛳️" },
  "engine+boat": { name: "Submarine", emoji: "🛳️" },
  "ship+engine": { name: "Submarine", emoji: "🛳️" },
  "engine+ship": { name: "Submarine", emoji: "🛳️" },
  "metal+sea": { name: "Submarine", emoji: "🛳️" },
  "sea+metal": { name: "Submarine", emoji: "🛳️" },
  "metal+ocean": { name: "Submarine", emoji: "🛳️" },
  "ocean+metal": { name: "Submarine", emoji: "🛳️" },

  "plane+water": { name: "Seaplane", emoji: "🛩️" },
  "water+plane": { name: "Seaplane", emoji: "🛩️" },
  "plane+human": { name: "Pilot", emoji: "✈️" },
  "human+plane": { name: "Pilot", emoji: "✈️" },
  "plane+fire": { name: "Crash", emoji: "💥" },
  "fire+plane": { name: "Crash", emoji: "💥" },

  "electricity+human": { name: "Shock", emoji: "⚡" },
  "human+electricity": { name: "Shock", emoji: "⚡" },
  "electricity+water": { name: "Danger", emoji: "⚠️" },
  "water+electricity": { name: "Danger", emoji: "⚠️" },
  "electricity+machine": { name: "Computer", emoji: "💻" },
  "machine+electricity": { name: "Computer", emoji: "💻" },
  "electricity+metal": { name: "Wire", emoji: "🔌" },
  "metal+electricity": { name: "Wire", emoji: "🔌" },

  "computer+human": { name: "Programmer", emoji: "👨‍💻" },
  "human+computer": { name: "Programmer", emoji: "👨‍💻" },
  "computer+computer": { name: "Internet", emoji: "🌐" },

  "internet+human": { name: "Gamer", emoji: "🎮" },
  "human+internet": { name: "Gamer", emoji: "🎮" },

  "plasma+earth": { name: "Star", emoji: "⭐" },
  "earth+plasma": { name: "Star", emoji: "⭐" },
  "plasma+wind": { name: "Aurora", emoji: "🌌" },
  "wind+plasma": { name: "Aurora", emoji: "🌌" },

  "star+water": { name: "Reflection", emoji: "✨" },
  "water+star": { name: "Reflection", emoji: "✨" },
  "star+earth": { name: "Meteor", emoji: "☄️" },
  "earth+star": { name: "Meteor", emoji: "☄️" },
  "star+star": { name: "Galaxy", emoji: "🌌" },
  "star+fire": { name: "Supernova", emoji: "💥" },
  "fire+star": { name: "Supernova", emoji: "💥" },

  "galaxy+earth": { name: "Universe", emoji: "🌌" },
  "earth+galaxy": { name: "Universe", emoji: "🌌" },
  "galaxy+human": { name: "Astronaut", emoji: "👨‍🚀" },
  "human+galaxy": { name: "Astronaut", emoji: "👨‍🚀" },

  "universe+human": { name: "Philosophy", emoji: "🤔" },
  "human+universe": { name: "Philosophy", emoji: "🤔" },
  "universe+life": { name: "Alien", emoji: "👽" },
  "life+universe": { name: "Alien", emoji: "👽" },

  "meteor+earth": { name: "Crater", emoji: "🕳️" },
  "earth+meteor": { name: "Crater", emoji: "🕳️" },
  "meteor+life": { name: "Extinction", emoji: "💀" },
  "life+meteor": { name: "Extinction", emoji: "💀" },

  "cook+fire": { name: "Chef", emoji: "👨‍🍳" },
  "fire+cook": { name: "Chef", emoji: "👨‍🍳" },
  "cook+fruit": { name: "Pie", emoji: "🥧" },
  "fruit+cook": { name: "Pie", emoji: "🥧" },

  "fruit+water": { name: "Juice", emoji: "🧃" },
  "water+fruit": { name: "Juice", emoji: "🧃" },
  "fruit+fire": { name: "Jam", emoji: "🫐" },
  "fire+fruit": { name: "Jam", emoji: "🫐" },
  "fruit+human": { name: "Farmer", emoji: "👨‍🌾" },
  "human+fruit": { name: "Farmer", emoji: "👨‍🌾" },

  "flower+water": { name: "Garden", emoji: "🌻" },
  "water+flower": { name: "Garden", emoji: "🌻" },
  "flower+fire": { name: "Perfume", emoji: "💐" },
  "fire+flower": { name: "Perfume", emoji: "💐" },
  "flower+human": { name: "Bouquet", emoji: "💐" },
  "human+flower": { name: "Bouquet", emoji: "💐" },
  "flower+love": { name: "Romance", emoji: "💕" },
  "love+flower": { name: "Romance", emoji: "💕" },

  "garden+human": { name: "Gardener", emoji: "👨‍🌾" },
  "human+garden": { name: "Gardener", emoji: "👨‍🌾" },
  "garden+house": { name: "Park", emoji: "🏞️" },
  "house+garden": { name: "Park", emoji: "🏞️" },

  "farmer+earth": { name: "Farm", emoji: "🌾" },
  "earth+farmer": { name: "Farm", emoji: "🌾" },
  "farmer+animal": { name: "Livestock", emoji: "🐄" },
  "animal+farmer": { name: "Livestock", emoji: "🐄" },

  "farm+animal": { name: "Cow", emoji: "🐄" },
  "animal+farm": { name: "Cow", emoji: "🐄" },
  "farm+water": { name: "Irrigation", emoji: "💧" },
  "water+farm": { name: "Irrigation", emoji: "💧" },

  "cow+fire": { name: "Steak", emoji: "🥩" },
  "fire+cow": { name: "Steak", emoji: "🥩" },
  "cow+human": { name: "Milk", emoji: "🥛" },
  "human+cow": { name: "Milk", emoji: "🥛" },

  "milk+fire": { name: "Cheese", emoji: "🧀" },
  "fire+milk": { name: "Cheese", emoji: "🧀" },
  "milk+human": { name: "Baby", emoji: "👶" },
  "human+milk": { name: "Baby", emoji: "👶" },

  "cheese+bread": { name: "Sandwich", emoji: "🥪" },
  "bread+cheese": { name: "Sandwich", emoji: "🥪" },

  "wheat+fire": { name: "Bread", emoji: "🍞" },
  "fire+wheat": { name: "Bread", emoji: "🍞" },
  "wheat+water": { name: "Beer", emoji: "🍺" },
  "water+wheat": { name: "Beer", emoji: "🍺" },

  "farm+plant": { name: "Wheat", emoji: "🌾" },
  "plant+farm": { name: "Wheat", emoji: "🌾" },
};

export function getRecipe(element1: string, element2: string): Recipe | null {
  const key = `${element1.toLowerCase()}+${element2.toLowerCase()}`;
  return recipes[key] || null;
}

export function getAllRecipes(): Record<string, Recipe> {
  return recipes;
}

